=== Rodez-IUT/dut-info2-filmprovider-DorianGayraud/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!-- Une librarie est composé d'un en-tête et d'au moins 1 livre -->
<!ELEMENT librairie (enTete, livre+) >

    <!-- Entitées pour le nom et prenom d'un auteur -->
    <!ENTITY % contact "(nom, prenom?)" >
        <!ELEMENT nom (#PCDATA) >
        <!ELEMENT prenom (#PCDATA) >

    <!-- Entitées pour méler texte et Balise GTML (em, strong, img) -->
    <!ENTITY % texteHTML "(#PCDATA|em|strong|img)*">
        <!ELEMENT em (#PCDATA) >
        <!ELEMENT strong (#PCDATA) >
        <!ELEMENT img EMPTY >
        <!ATTLIST img src CDATA #REQUIRED
                title CDATA #IMPLIED >

    <!-- Entité permettant d'inserer "©Librairie & Internet 2020" dans l'en-tête -->
    <!ENTITY copyright "©Librairie &amp; Internet 2020" >

    <!-- En-tête = texte libre ref to texteHTML pour plus d'infos -->
    <!ELEMENT enTete %texteHTML;>
    <!-- Un livre est identifiée de manière unique par un numero ISBN -->
    <!ELEMENT livre (titre, auteur+, description, prix) >
        <!ATTLIST livre ISBN NMTOKEN #REQUIRED >
        <!ELEMENT titre (#PCDATA) >
        <!-- Auteur soit sous forme de liste soit sous forme d'un unique element -->
        <!ELEMENT auteur ((%contact;)*|collectif) >
            <!ELEMENT collectif (direction, membres)>
            <!ELEMENT direction (%contact;) >
            <!ELEMENT membres (#PCDATA) >
        <!-- La description est semblable à l'en-tête, texte et balises HTML mêlés. -->
        <!ELEMENT description %texteHTML;>
        <!ELEMENT prix (#PCDATA) >
            <!ATTLIST prix devise (euros|livre|dollar) "euros"
                           type (HT|TTC) "HT"
                           tva CDATA #FIXED "5.5">

=== Rodez-IUT/dut-info2-filmprovider-DorianGayraud/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd" >

<librairie>
    <enTete>
        Bonjour, Bienvenue dans cette <em>magnifique</em> librairie de
        <strong>NAUCELLE</strong>, livre à tout prix et pour tous !
        <img src=""></img>
        &copyright;
    </enTete>
    <livre ISBN="151_151">
        <titre>Croc-Blanc</titre>
        <auteur>
            <nom>London</nom>
            <prenom>Jack</prenom>
        </auteur>
        <description>
            L'histoire commence à la naissance de
            Croc-Blanc, un chien-loup. Le roman suit la meute
            d'où il vient et ses premières semaines de vie sauvage,
            sa lutte pour la vie : manger ou être mangé. ...
            Il rencontre d'autres chiens et devient ennemi avec eux,
            Lip-Lip étant son rival.
        </description>
        <prix devise="euros" tva="5.5" type="TTC">150</prix>
    </livre>
    <livre ISBN="152-15285">
        <titre>Influence et Manipulation</titre>
        <auteur>
            <nom>CIALDINI</nom>
            <prenom>Robert</prenom>
        </auteur>
        <description>Pourquoi et comment sommes-nous amenés à
            faire des choses contre notre gré ?
            Robert Cialdini, docteur en psychologie sociale,
            livre le résultat de plus de quinze ans de recherches
            sur les mécanismes et les techniques de persuasion.
            Dans ce livre, il explique pourquoi certaines
            personnes sont douées d'un remarquable talent de
            persuasion et comment il est possible de les battre
            sur leur propre terrain. Ce document nous dévoile
            les six secrets psychologiques qui se cachent
            derrière notre dangereuse tendance à nous laisser
            influencer, ainsi que les moyens employés par les
            spécialistes de la persuasion pour les exploiter à
            notre insu. Il nous apprend à nous en défendre, en
            tournant ces secrets à notre avantage.  Grâce à ce
            livre indispensable, vous ne direz plus jamais
            « Oui », alors que vous pensez « non ».</description>
        <prix devise="dollar" type="TTC" tva="5.5">800</prix>
    </livre>
</librairie>
